services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  # Mount backend for live code updates
    ports:
      - "8080:8080"
    env_file:
      - backend/.env  # Removed "backend/" since context is already backend
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs are immediately flushed
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r=requests.get('http://localhost:8080/health'); exit(0) if r.status_code == 200 else exit(1)"]
      interval: 10s
      retries: 3
    networks:
      - mancala-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Matches the configured Vue port for dev mode
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    env_file:
      - frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mancala-network

networks:
  mancala-network:
    driver: bridge
