name: Pull Request Checks

on:
  push:
    branches: [ main, production, dev ]  # Triggers on direct pushes to these branches
  pull_request:
    branches: [ main, production, dev ]  # Require checks on these branches

jobs:
  lint:
    name: Run flake8 linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'  # Adjust based on your project needs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Run flake8 linting
        run: flake8 your_project/ --max-line-length 88
